import nats
import sqlite3
import time
import argparse
import asyncio

parser = argparse.ArgumentParser(description='Infrared Sensor Reader')

parser.add_argument('--sensor-type', type=str, choices=['mockup', 'real'], required=True,
                    help='Sensor type: "mockup" or "real"')
parser.add_argument('--reading-frequency', type=int, required=True,
                    help='Reading frequency in seconds')
parser.add_argument('--min-value', type=int, help='Minimum value generated by the sensor (for "mockup" type)')
parser.add_argument('--max-value', type=int, help='Maximum value generated by the sensor (for "mockup" type)')
parser.add_argument('--db-uri', type=str, required=True,
                    help='URI to the SQL database')

args = parser.parse_args()
args_dict = {key: value for key, value in vars(args).items()}
print('==== Arguments ====')
for key, value in args_dict.items():
    print(f"{key:<20} {value}")
print('===================')